 # This is a config for E2B sandbox template.
# You can use template ID (z64szow1usze102d8l0j) or template name (vibe-nextjs-new-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-new-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-new-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-new-test-2')

team_id = "9878f3c7-c3c9-4f45-add8-167b67d87237"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-new-test-2"
template_id = "z64szow1usze102d8l0j"
